### ISSUE TITLE
semantic-release-cli is not a devDependency?

### ISSUE THREAD

**Issue by ZebraFlesh** [motiz88/git-exec-and-restage#21]
`semantic-release-cli` is [listed as a production dependency ](https://github.com/motiz88/git-exec-and-restage/blob/master/package.json#L48) instead of a devDependecy as recommended in their readme. This adds significant size to downstream consumers because it requires an installation of npm and and the associated node-gyp.  Output from `yarn why npm` yields "This module exists because "git-exec-and-restage#semantic-release-cli" depends on it."

**Comment by ZebraFlesh** [comment]
Clarification: the `semantic-release-cli` package is completely unneeded. The `semantic-release` package by itself is sufficient.

**Comment by JLHwung** [comment]
You can try
```
npm install @easyops/git-exec-and-restage
```
for a realistic dependency size.

**Comment by motiz88** [comment]
Closed #21 via #13.
